---

- include_tasks: variables.yml

- include_tasks: core/install.yml

- include_tasks: core/apps.yml

- include_tasks: core/integrity.yml

- include_tasks: core/upgrade.yml

- include_tasks: core/config.yml

- include_tasks: users/user.yml

- include_tasks: users/group.yml

- include_tasks: users/user_config.yml

- include_tasks:
    file: apps/news.yml
    apply:
      become: false
