---

# Read all apps shipped by Nextcloud itself
- name: Read shipped apps
  command: ./occ app:list --shipped=true --no-warnings --output=json
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  register: _result
  changed_when: false

- name: Remove non-json text from command output
  set_fact:
    nextcloud_shipped_apps: "{{ _result.stdout | from_json }}"

# Read all external apps which have been installed by in addition
- name: Read installed external apps
  command: ./occ app:list --shipped=false --no-warnings --output=json
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  register: _result
  changed_when: false

- name: Remove non-json text from command output
  set_fact:
    nextcloud_installed_apps: "{{ _result.stdout | from_json }}"

# Remove all apps from the list of external apps which are not in the
# configured list of apps, if nextcloud_remove_unknown_apps is set to true
- name: Remove unknown external apps
  command: php occ app:remove "{{ item }}"
  with_items: "{{ (nextcloud_installed_apps.enabled |
    combine(nextcloud_installed_apps.disabled)) }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: result
  failed_when: result.stdout is not search('removed') or result is failed
  changed_when: result is not failed
  when:
    - nextcloud_remove_unknown_apps
    - not (nextcloud_apps | selectattr('name', 'search', item) | list)

# Remove all apps which have their state set to "absent"
- name: Remove external apps
  command: php occ app:remove "{{ item.name }}"
  with_items: "{{ nextcloud_apps }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: result
  failed_when: result.stdout is not search('removed') or result is failed
  changed_when: result is not failed
  when:
    - item.name in (nextcloud_installed_apps.enabled
      | combine(nextcloud_installed_apps.disabled))
    - item.state | default('enabled') == 'absent'

# Install all apps from the configured list which
# - are external apps (not in the shipped apps list) and
# - are not yet installed (not in the installed apps list) and
# - have their state not set to "absent"
- name: Install external apps
  command: php occ app:install "{{ item.name }}"
  with_items: "{{ nextcloud_apps }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: result
  failed_when: result.stdout is not search('installed') or result is failed
  changed_when: result is not failed
  when:
    - item.name not in (nextcloud_shipped_apps.enabled
      | combine(nextcloud_shipped_apps.disabled))
    - item.name not in (nextcloud_installed_apps.enabled
      | combine(nextcloud_installed_apps.disabled))
    - item.state | default('enabled') != 'absent'

# Update list of available apps after installation and removal:
- name: Re-read installed external apps
  command: ./occ app:list --shipped=false --no-warnings --output=json
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  register: _result
  changed_when: false

- name: Remove non-json text from command output
  set_fact:
    nextcloud_installed_apps:  "{{ _result.stdout | from_json }}"

# Check and update all external apps
- name: Update external apps
  command: php occ app:update "{{ item }}"
  with_items: "{{ (nextcloud_installed_apps.enabled
    | combine(nextcloud_installed_apps.disabled)) }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: result
  failed_when: result.stdout is search('not installed') or result is failed
  changed_when: result.stdout is search('updated') and result is not failed

# Enable all apps from the configured list which
# - are not yet enabled and
# - have their state set to "enabled"
- name: Enable apps
  command: ./occ app:enable "{{ item.name }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  with_items: "{{ nextcloud_apps }}"
  when:
    - (item.state | default('enabled')) == 'enabled'
    - item.name not in (nextcloud_installed_apps.enabled
      | combine(nextcloud_shipped_apps.enabled))

# Disable all apps from the configured list which
# - are not yet disabled and
# - have their state set to "disabled"
- name: Disable apps
  command: ./occ app:disable "{{ item.name }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  with_items: "{{ nextcloud_apps }}"
  when:
    - (item.state | default('enabled')) == 'disabled'
    - item.name not in (nextcloud_installed_apps.disabled
      | combine(nextcloud_shipped_apps.disabled))
